name: "NPM Publish Next"

on:
  push:
    branches:
      - next
      
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Node
              uses: actions/setup-node@v4
              with:
                node-version: 22
                registry-url: https://registry.npmjs.org
            - run: npm install
            ## PUBLISH PACKAGE ##
            - name: Publish
              run: npm publish --tag next --provenance --access public
              working-directory: ./
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}